### ISSUE TITLE
What are train_interval, nb_steps_warmup_critic and nb_steps_warmup_actor?

### ISSUE THREAD

**Issue by ViktorM** [keras-rl/keras-rl#109]
What are train_interval, nb_steps_warmup_critic and nb_steps_warmup_actor in terms of the **Algorithm 1 DDPG pseudocode** in the original paper?

**Comment by ViktorM** [comment]
Also can you comment to what parts backward and forward passes are related to the pseudocode?

**Comment by Beliefuture** [comment]
Have you found the answer yet? Moreover, how to balance and set the proper value of the arguments ```nb_steps_warmup``` and ```nb_steps``` ? The official documentation is not so detailed.
