### ISSUE TITLE
why

### ISSUE THREAD

**Issue by zhoudoudou** [keras-rl/keras-rl#115]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question in the [Keras-RL Google group](https://groups.google.com/forum/#!forum/keras-rl-users) or [join the Keras-RL Gitter channel](https://gitter.im/keras-rl/Lobby) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras-RL. You can update with:
`pip install git+git://github.com/matthiasplappert/keras-rl.git --upgrade --no-deps`

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps`

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short). If you report an error, please include the error message and the backtrace.

**Comment by cserpell** [comment]
I think this issue should be closed.

**Comment by RaphaelMeudec** [comment]
An issue template is available, thanks for the checklist!
