### ISSUE TITLE
Inverting Gradients

### ISSUE THREAD

**Issue by csianglim** [keras-rl/keras-rl#121]
Not sure if this project is still actively maintained but here's my issue.

I'm trying to add inverting gradients to DDPG.py (something like the BoundingLayer class [in this file](https://github.com/karolkuna/reinforcement-learning/blob/be3a8a17058841441ad7b326f904f8bfa99cce39/layers.py), and based on [this paper](https://pdfs.semanticscholar.org/49da/57cf2900cd50d64a6d63d45e1bccd454fcbb.pdf)). I'm having some trouble with the implementation because I'm not quite sure how to access the gradients correctly.

Here's my attempt: https://github.com/csianglim/keras-rl/blob/723b75110a7e2544316db96a8cd186eef956054b/rl/agents/ddpg.py

The error is `ValueError: Shape must be rank 0 but is rank 2 for 'cond/Switch' (op: 'Switch') with input shapes: [2,400], [2,400]`

Tagging @Phylliade since `vinci` appears to be active.

**Comment by Phylliade** [comment]
Hi @csianglim,

Actually, you're more than right, we're currently working on the gradient inverting feature on vinci too!

We plan to switch the gradient computation to a pure TF implementation, to make it easier to expand, and implement gradient inverting from it.
It should land in the beginning of next week in vinci's code.

**Comment by csianglim** [comment]
Awesome, looking forward to it!

**Comment by RikSaint55555** [comment]
I @csianglim and @Phylliade,

I'm using rl-keras on a rdpg research project. I was trying to do same thing, implement the "inverting gradient", and I found this old but very relevant thread. Were there any progress? Have you managed putting it to work, @csianglim?

Many tks!
