### ISSUE TITLE
OpenAI episodes vs steps

### ISSUE THREAD

**Issue by filmo** [keras-rl/keras-rl#123]
It seems like this framework trains for N steps rather than N episodes. 

When I use the env.wrapper.Monitor() to encapsulate the results for upload to OpenAI gym site, I'm getting a "can't reset a non-done environment error"

```
Error("Tried to reset environment which is not done. While the monitor is active for {}, you cannot call reset() unless the episode is over.".format(self.env_id))
gym.error.Error: Tried to reset environment which is not done. While the monitor is active for LunarLander-v2, you cannot call reset() unless the episode is over.
```

Is there a way with this framework to train based on a number of episode rather than just a fixed number of steps. Using the 'nb_steps'  means that the last episode will likely be 'in-progress' when training finishes.

Perhaps there's some simple setting I over looked, but I didn't see it.

**Comment by filmo** [comment]
One thing I did was adjust the example so as to 'burn off' the remaining steps in the environment

```
# After training is done, we save the final weights.
dqn.save_weights('dqn_{}_weights.h5f'.format(ENV_NAME), overwrite=True)

# burn off the remaning steps of the episode
done = False
while not done:
    _,_,done,_ = env.step(0)

# Finally, evaluate our algorithm for 5 episodes.
dqn.test(env, nb_episodes=5, visualize=True)
```
Seems a little inelegant, but worked to resolve the issue.

**Comment by ruippeixotog** [comment]
I'm also having the same problem. Shouldn't keras-rl train always until the end of the last episode, even if it results in more steps? At least an option to do that would be nice.
