### ISSUE TITLE
How to resume training using CEM agent

### ISSUE THREAD

**Issue by marekyggdrasil** [keras-rl/keras-rl#127]
Hello. I was wondering if you could instruct me how to resume training of a model (in my case `cem`).

### what I did

1. run cem agent as stated in the [example](https://github.com/matthiasplappert/keras-rl/blob/a02079e86d5febfb469f26b478e2e2fe421284a8/examples/cem_cartpole.py)
2. run the same example again but this time I used [load_weights](https://github.com/matthiasplappert/keras-rl/blob/a02079e86d5febfb469f26b478e2e2fe421284a8/rl/core.py#L400) method

## results I obtained

It doesn't seem training is being continued, rather it looks like it starts over,

Test after first run

```
Testing for 5 episodes ...
Episode 1: reward: -0.904, steps: 22
Episode 2: reward: -0.904, steps: 22
Episode 3: reward: -0.904, steps: 22
Episode 4: reward: -0.904, steps: 22
Episode 5: reward: -0.904, steps: 22
```

Test after second run

```
Testing for 5 episodes ...
Episode 1: reward: -0.973, steps: 4
Episode 2: reward: -0.973, steps: 4
Episode 3: reward: -0.973, steps: 4
Episode 4: reward: -0.973, steps: 4
Episode 5: reward: -0.973, steps: 4
```

Clearly, weights after first run gave much better results, yet those were abandoned and replaced with ones from second training.

Is there a way to resume training at least for CEM agent? Any way to take advantage of previous runs?

**Comment by r-lipton** [comment]
I have this problem too with the DQN.
Did you find the solution @marekyggdrasil ? Any ideas @matthiasplappert ?

**Comment by marekyggdrasil** [comment]
I didn't find anything, unfortunately.
