### ISSUE TITLE
TypeError when datetime object is included in environment info output

### ISSUE THREAD

**Issue by MADindustries** [keras-rl/keras-rl#140]
Suppose the output of an env step produces:

`(array([[1,2,3,4],[1,2,3,4]]), 0.0, False, {'step': 2, 'time': datetime.datetime(2017, 5, 3, 0, 30)})`

Where the fourth item in the list is the 'info'.  [Line 173 of core.py](https://github.com/matthiasplappert/keras-rl/blob/master/rl/core.py#L173) will consider the 'time' value to be real because `np.isreal(datetime.datetime(2017, 5, 3, 0, 30))` = True

The code then attempts to `accumulated_info['time'] += datetime.datetime(2017, 5, 3, 0, 30)` which fails of course because you cannot add two datetime objects in this way.

**Comment by matthiasplappert** [comment]
Oh boy. Maybe the right thing to do here is to check if the type supports addition and multiplication instead.
