### ISSUE TITLE
TensorBoard callback doesn't work

### ISSUE THREAD

**Issue by ruippeixotog** [keras-rl/keras-rl#141]
When I try to add a TensorBoard callback in [dqn_cartpole.py](https://github.com/matthiasplappert/keras-rl/blob/master/examples/dqn_cartpole.py), like:

```python
# (...)
from keras.callbacks import TensorBoard
tb_log_dir = 'logs/tmp'
tb_callback = TensorBoard(log_dir=tb_log_dir, histogram_freq=1)
dqn.fit(env, nb_steps=50000, visualize=True, verbose=2, callbacks=[tb_callback])
# (...)
```

The `fit` method fails with:

```
Traceback (most recent call last):
  File "dqn_cartpole.py", line 49, in <module>
    dqn.fit(env, nb_steps=50000, visualize=True, verbose=2, callbacks=[tb_callback])
  File "venv/lib/python3.6/site-packages/rl/core.py", line 215, in fit
    callbacks.on_episode_end(episode, episode_logs)
  File "venv/lib/python3.6/site-packages/rl/callbacks.py", line 59, in on_episode_end
    callback.on_epoch_end(episode, logs=logs)
  File "venv/lib/python3.6/site-packages/keras/callbacks.py", line 783, in on_epoch_end
    summary_value.simple_value = value.item()
AttributeError: 'float' object has no attribute 'item'
```

Am I doing something wrong?

**Comment by vk99** [comment]
Same issue here.. looks like compatibility with Keras callbacks is broken.. simplest workaround is to edit problematic line (783 for Keras 2.0.6; 793 for Keras 2.0.8) in keras\callbacks.py:

summary_value.simple_value = value.item()
to
summary_value.simple_value = value

**Comment by guillem74** [comment]
@vk99 still not working

**Comment by RaphaelMeudec** [comment]
Fixed this, get the last release!

**Comment by drag05** [comment]
I run keras on R Studio with tensorflow-gpu 2.0.0 back-end. Tensorboard callback doesn't work. Still. 
Please help!
