### ISSUE TITLE
Compatibility issue with Keras 2.0 

### ISSUE THREAD

**Issue by hesenp** [keras-rl/keras-rl#143]
Hey there, 

I realized that there are some compatibility issue with Keras 2.0. For examples, signatures from keras-rl is already different from what is supported in Keras. Do we have plans to get compatible? 

Examples: 
Signatures from keras-rl: 

[in keras-rl](https://github.com/matthiasplappert/keras-rl/blob/8961e3a83bad8915db44e67099cbcccb72355b07/rl/util.py#L93)
```
    def get_updates(self, params, constraints, loss):
```

[in keras current version](https://github.com/fchollet/keras/blob/62d097c4ff6fa694a4dbc670e9c7eb9e2bc27c74/keras/optimizers.py#L155)
```
    def get_updates(self, loss, params):
```

Alas I tried to take a stab at above and after the change another few errors popped up somewhere else. I guess we might need someone more familiar with keras-rl to make that change happen.

**Comment by RaphaelMeudec** [comment]
Hey,

I'm closing this issue as it's been handled in https://github.com/keras-rl/keras-rl/pull/144 

Thanks for pointing out the problem!
