### ISSUE TITLE
Feature request: np_episodes as new option to fit()

### ISSUE THREAD

**Issue by AxKo** [keras-rl/keras-rl#161]
Hi,
I recently discovered keras-rl and noticed that it is possible to specify the number of steps for fitting, but not the number of episodes. I would find that a very useful feature and it only requires to change a few lines of code in core.py. 
I did that in my installation, but it would be nice to have it in the official distribution. So this would be my feature request for the next release. I'm also happy to somehow provide my code changes if somebody tells me the best way to do this (I'm not so familiar with github).

Many thanks,
   Axel

**Comment by Sat0ri** [comment]
>AxKo 
 I did that in my installation, ...

How you did it?

**Comment by AxKo** [comment]
Make the following changes to your site-packages\rl\core.py file:

Around line 40:
    def fit(self, env, nb_steps=0, nb_episodes=0, action_repetition=1, callbacks=None, verbose=1,

Around line 100:
        params = {
            'nb_steps': nb_steps,
            'nb_episodes': nb_episodes,         
        }

And around line 115:
        while self.step<nb_steps or episode<nb_episodes:


Now you can specify nb_steps OR nb_episodes in the call to fit()

Best regards,
  Axel

**Comment by AxKo** [comment]
Oh, and if this finds its way into a new release it would be helpful to make 'episode' an instance variable (self.episode) in core.py. That way also Policies can work on episodes instead of steps.

Thanx,
  Axel

**Comment by Sat0ri** [comment]
Thanks a lot.. it works but, need to change ...

> Around line 40:
def fit(self, env, nb_steps=0, nb_episodes=0, action_repetition=1, callbacks=None, verbose=1,

**to** 

def fit(self, env, **nb_steps=1**, nb_episodes=0, action_repetition=1, callbacks=None, verbose=1,

Very usefull! Thanx

**Comment by Sat0ri** [comment]
I also add best reward...

**1)**
>def fit(self, env, nb_steps=1, nb_episodes=0, **br=0**, action_repetition=1, callbacks=None, verbose=1,

**2)** before ` if done:` Around line 205:

>if br != 0 and episode_reward >= br:
>done = True
>break

So, now it finish learning if it reach desired reward before it reach end of nb_episodes

500 for 'CartPole-v1', for example:
> dqn.fit(env, nb_episodes=nb_Episodes, br=500, visualize=False, verbose=2)

**Comment by pollini** [comment]
Hi @Sat0ri , could you explain why someone would want to define a 'best maximum reward' in advance?

**Comment by Sat0ri** [comment]
Hi @pollini , for example, train the net untill it reach **best** reward after save&test it.

This code:
`dqn.fit(env, nb_episodes=nb_ep, visualize=False, verbose=2)`
`dqn.save_weights('Saved/weights.h5f', overwrite=True)`

...sometimes when it training for **_n_** episodes it reach best reward early, but at the end of training the reward will be not the maximun, and it will save it anyway

this one: 
`dqn.fit(env, nb_episodes=nb_ep, **br=best_reward**, visualize=False, verbose=2)
dqn.save_weights('Saved/weights.h5f', overwrite=True)`
will save weights with best reward/results.

**Comment by campbelljc** [comment]
I agree with this proposal. Depending on the environment, and if episodes can be of arbitrary length, it's harder to compare the results of two models since one may have gone through many more episodes than the other if we use number of actions as the stopping criterion.

**Comment by nuqz** [comment]
Thank you all, guys. I wish this feature too, it's very useful in some cases.

**Comment by wtesler** [comment]
This would also be very useful for my use case.

**Comment by CameronBeebe** [comment]
I just tried to pass nb_episodes to .fit... but its not a kwarg, but is for .test.  Seemed like an obvious way to handle #123 .
