### ISSUE TITLE
Why custom ringbuffer used instead of deque?

### ISSUE THREAD

**Issue by kirkscheper** [keras-rl/keras-rl#165]
https://github.com/matthiasplappert/keras-rl/blob/d9e3b64a20f056030c02bfe217085b7e54098e48/rl/memory.py#L42 states:
Do not use deque to implement the memory. This data structure may seem convenient but it is way too slow on random access. Instead, we use our own ring buffer implementation.

Not sure why this is stated. I ran this quick test:
`
    ring = RingBuffer(maxlen = 1000)
    
    start_time = time.time()
    for i in range(100000):
        ring.append(i)
    print("--- %s seconds ---" % (time.time() - start_time))
    
    d = deque(maxlen=1000)
    start_time = time.time()
    for i in range(100000):
        d.append(i)
    print("--- %s seconds ---" % (time.time() - start_time))
    
    start_time = time.time()
    for i in range(100000):
        l = ring[i%1000-1]
    print("--- %s seconds ---" % (time.time() - start_time))
    
    start_time = time.time()
    for i in range(100000):
        l = d[i%1000]
    print("--- %s seconds ---" % (time.time() - start_time))
`
and got this result:
`
--- 0.0608789920807 seconds ---
--- 0.00712609291077 seconds ---
--- 0.0430929660797 seconds ---
--- 0.00617289543152 seconds ---
`

You can see that the custom ringbuffer is significantly slower than the deque at adding or removing. Can someone explain to me what the comment is referring to exactly and why the ringbuffer is used?

**Comment by matthiasplappert** [comment]
Was this benchmark done using Python 3 or Python 2.7? I remember that I had trouble with deque and Python 2.7 in the past, but I may be wrong.

**Comment by kirkscheper** [comment]
It was with python 2.7, with python 3 I get this:
--- 0.07599091529846191 seconds ---
--- 0.01183772087097168 seconds ---
--- 0.060945987701416016 seconds ---
--- 0.014749526977539062 seconds ---

Here the deque is a bit slower but still much faster then the ring buffer.

**Comment by matthiasplappert** [comment]
Could you do a benchmark with truly random access? It seems like you go through the buffer in sequential order. Instead, try something where you randomly draw indices.

If this test turns out to show the same trend, feel free to remove the custom `RingBuffer` with `deque`.

**Comment by kirkscheper** [comment]
with this code:
    idxs = []
    r = xrange(0, 1000)
    for i in range(100000):
      idxs.append(random.sample(r, 1))
      
    ring = RingBuffer(maxlen = 1000)
    start_time = time.time()
    for i in range(100000):
        ring.append(i)
    print("--- %s seconds ---" % (time.time() - start_time))

    d = deque(maxlen=1000)
    start_time = time.time()
    for i in range(100000):
        d.append(i)
    print("--- %s seconds ---" % (time.time() - start_time))

    start_time = time.time()
    for i in range(100000):
        l = ring[idxs[i][0]]
    print("--- %s seconds ---" % (time.time() - start_time))

    start_time = time.time()
    for i in range(100000):
        l = d[idxs[i][0]]
    print("--- %s seconds ---" % (time.time() - start_time))

I get this for python2.7:
--- 0.0610370635986 seconds ---
--- 0.00898694992065 seconds ---
--- 0.0499200820923 seconds ---
--- 0.0144419670105 seconds ---

and for python 3:
--- 0.07166552543640137 seconds ---
--- 0.012346744537353516 seconds ---
--- 0.06459164619445801 seconds ---
--- 0.015827417373657227 seconds ---

Indeed the random access in Python2.7 is about half the speed of sequential access but still faster than the ring buffer.

**Comment by matthiasplappert** [comment]
Cool, feel free to update the code to use `deque`. I'm not sure anymore why I thought `deque` was too slow but it seems like this was clearly not true.

**Comment by luffy1996** [comment]
@matthiasplappert, @kirkscheper  Please let me know if anyone is working on this. I will be glad to finish this as soon as possible.

**Comment by RaphaelMeudec** [comment]
@luffy1996 Feel free to work on this, I don't think anyone it tackling this issue at the moment!

**Comment by luffy1996** [comment]
@RaphaelMeudec  Give me a week. My semester exams are going on. I would love to work on this from next week.

**Comment by RaphaelMeudec** [comment]
No pressure, good luck on your exams!

**Comment by buckleytoby** [comment]
hey @kirkscheper ! I'm interested in the deque implementation, do you have any progress from above?

**Comment by kirkscheper** [comment]
All my changes are here: https://github.com/kirkscheper/keras-rl/tree/recurrent-ddpg

I have been playing around with lots of different things that are probably not directly ready for a pull request.

**Comment by sperazza** [comment]
the comments above, with performance testing are correct, deque is faster, for appends.  but the slowdown comes with random.sample(dq,batch_size), when you are sampling a large buffer.  the implementation given for RingBuffer (via SequentialMemory), in both python 2.7 and 3+ is about 10x faster for Sampling. 

my performance runs for sampling( size 1,000,000) were:
random sampling of deque: 5.98 secs
random sampling of RingBuffer .574 secs

so... use the RingBuffer(SequentialMemory class), it samples way faster, and is on about the same *magnitude* for append().

**Comment by matthiasplappert** [comment]
Ah yes, I remember that this was the reason for creating this custom implementation since fast random sampling is very important.

Thanks for looking into it.

**Comment by UPUPGOO** [comment]
@sperazza I did an experiment as you said, but I got an opposite result.
With this code:

    obs = np.resize(np.arange(9), (3, 3)).astype(np.uint8)
    a = 0
    r = 1.0
    done = False

    ring = SequentialMemory(limit=10000,window_length=4)
    start_time = time.time()
    for i in range(10000):
        ring.append(obs, a, r, done)
    print("--- %s seconds ---" % (time.time() - start_time))

    start_time = time.time()
    for i in range(10000):
        ring.sample(batch_size=32)
    print("--- %s seconds ---" % (time.time() - start_time))

And I got this for RingBuffer:
 --- 0.039894819259643555 seconds ---
 --- 15.629229307174683 seconds ---
When I replace RingBuffer with deque in SequentialMemory  class like this:

    self.actions = deque(maxlen=limit)
    self.rewards = deque(maxlen=limit)
    self.terminals = deque(maxlen=limit)
    self.observations = deque(maxlen=limit)

I got this:
--- 0.031911611557006836 seconds ---
--- 9.875584602355957 seconds ---
So I am confused. Is there some problems with my code?
Thanks.

**Comment by clarisli** [comment]
@UPUPGOO if you read the `RingBuffer` class https://github.com/keras-rl/keras-rl/blob/e6efb0d8297ec38d704a3110b5d6ed74d09a05e3/rl/memory.py#L45-L83
and the `SequentialMemory` class
https://github.com/keras-rl/keras-rl/blob/e6efb0d8297ec38d704a3110b5d6ed74d09a05e3/rl/memory.py#L158-L195
Note that the RingBuffer has been updated using a deque, and `SequentialMemory` is using RingBuffer, so which means both are using deques.  

Now if you read the code from this function - `sample_batch_indexes()`
https://github.com/keras-rl/keras-rl/blob/e6efb0d8297ec38d704a3110b5d6ed74d09a05e3/rl/memory.py#L14-L42 
You will notice that now the code has been updated to always sampling from a list, so you were not doing the same deque/list sampling comparison as @sperazza did up there.
