### ISSUE TITLE
Vectors as actions

### ISSUE THREAD

**Issue by santient** [keras-rl/keras-rl#168]
I'm wondering if there is a way to set up keras-rl for environments that take vectors of floats as inputs (Box action space?) rather than one discrete action per iteration. Like a multi-discrete action space, but with floats instead of ints. Example:

    def step(self, action):
        self.state = numpy.add(self.state, action)
        etc...
state before: `[0, 0, 0.5, 0]`
action: `[0.1, 0.1, 0.4, 0]`
state after: `[0.1, 0.1, 0.9, 0]`

When I attempted to do this with DQNAgent, the action was scalar, not a vector as desired, and I got this error:

    IndexError                                Traceback (most recent call last)
    <ipython-input-51-fe5b5e993e1f> in <module>()
     54 # slows down training quite a lot. You can always safely abort the training prematurely using
     55 # Ctrl + C.
    ---> 56 cem.fit(env, nb_steps=100000, visualize=False, verbose=2)
     57 
     58 # After training is done, we save the best weights.

    ~/.local/lib/python3.6/site-packages/rl/core.py in fit(self, env, nb_steps, action_repetition, callbacks, verbose, visualize, nb_max_start_steps, start_step_policy, log_interval, nb_max_episode_steps)
    166                 for _ in range(action_repetition):
    167                     callbacks.on_action_begin(action)
    --> 168                     observation, r, done, info = env.step(action)
    169                     observation = deepcopy(observation)
    170                     if self.processor is not None:

    <ipython-input-45-5287207f4760> in step(self, actions)
     17         #print(actions)
     18         #actions = numpy.round(actions)
    ---> 19         self.state = numpy.add(self.state, numpy.array([actions[0], actions[1]]))
     20         #terminal = True
     21         #ones = numpy.count_nonzero(self.state)

    IndexError: invalid index to scalar variable.

**Comment by mattdornfeld** [comment]
I think you want to use DDPG rather than DQN. DQN is designed to work with discrete action spaces. DDPG is a generalization of DQN to continuous action spaces.
