### ISSUE TITLE
Implement Rainbow DQN extensions

### ISSUE THREAD

**Issue by pathway** [keras-rl/keras-rl#180]
Would be nice to have "rainbow" DQN extensions as described in https://arxiv.org/abs/1710.02298

raphaelmeudec on reddit suggested they might want to do this in keras-rl so here is the reminder: https://www.reddit.com/r/reinforcementlearning/comments/80u9ht/d_any_algorithms_you_would_like_to_see_implemented/dvujpme/

**Comment by RaphaelMeudec** [comment]
Our plan is first to merge A3C and PPO and then take a look at Rainbow implementation. Thanks for opening this!

**Comment by jheffez** [comment]
Hi, have you had a chance to look at rainbow?
