### ISSUE TITLE
Tensorboard callback fail 

### ISSUE THREAD

**Issue by guillem74** [keras-rl/keras-rl#188]
When calling Tensorboard callback, at epoch end

It throws an error at line 862:

summary_value.simple_value = value.item()

AttributeError: 'int' object has no attribute 'item'

**Comment by guillem74** [comment]
Changing:

summary_value.simple_value = value.item()
to
summary_value.simple_value = value

As said in other issues, it does not work for me.

**Comment by RaphaelMeudec** [comment]
Will dig into it over the next few days, I'll keep you updated!

**Comment by RaphaelMeudec** [comment]
Hi, fixed this issue in last release.
