### ISSUE TITLE
TypeError: update() got an unexpected keyword argument 'force'

### ISSUE THREAD

**Issue by susiwen8** [keras-rl/keras-rl#194]
I try to run dqn_atari.py on my PC, I have installed all dependencies, but I got this error

Traceback (most recent call last):
  File "dqn_atari.py", line 111, in <module>
    dqn.fit(env, callbacks=callbacks, nb_steps=1750000, log_interval=10000)
  File "/usr/local/lib/python3.5/dist-packages/rl/core.py", line 196, in fit
    callbacks.on_step_end(episode_step, step_logs)
  File "/usr/local/lib/python3.5/dist-packages/rl/callbacks.py", line 75, in on_step_end
    callback.on_step_end(step, logs=logs)
  File "/usr/local/lib/python3.5/dist-packages/rl/callbacks.py", line 245, in on_step_end
    self.progbar.update((self.step % self.interval) + 1, values=values, force=True)
TypeError: update() got an unexpected keyword argument 'force'

I check the code in callbacks.py, It seems that my keras version is below 2.1.3, but I have checked my keras is 2.1.5. 

So anyone call tell the problem?

**Comment by RaphaelMeudec** [comment]
Hey, can you provide your Python version, a log of `pip freeze` and a sample code so I can check this out easily? Thanks!

**Comment by susiwen8** [comment]
Sorry I think I have made a mistake, I check the code in Github not in my local PC, so in my local callback, it doesn't check keras version, so I has this problem. 

    def on_step_end(self, step, logs):
        if self.info_names is None:
            self.info_names = logs['info'].keys()
        values = [('reward', logs['reward'])]
        self.progbar.update((self.step % self.interval) + 1, values=values, force=True)
        self.step += 1
        self.metrics.append(logs['metrics'])
        if len(self.info_names) > 0:
            self.infos.append([logs['info'][k] for k in self.info_names])

In latest code it checks:
    def on_step_end(self, step, logs):
        """ Update progression bar at the end of each step """
        if self.info_names is None:
            self.info_names = logs['info'].keys()
        values = [('reward', logs['reward'])]
        if KERAS_VERSION > '2.1.3':
            self.progbar.update((self.step % self.interval) + 1, values=values)
        else:
            self.progbar.update((self.step % self.interval) + 1, values=values, force=True)
        self.step += 1
        self.metrics.append(logs['metrics'])
        if len(self.info_names) > 0:
            self.infos.append([logs['info'][k] for k in self.info_names])

My bad!

**Comment by RaphaelMeudec** [comment]
I'm gonna release a new version of keras-rl to prevent this from happening, thanks!
