### ISSUE TITLE
What's the plan to implement Rainbow DQN?

### ISSUE THREAD

**Issue by forhonourlx** [keras-rl/keras-rl#196]
What's the plan to implement Rainbow DQN?
Looking forward.

**Comment by RaphaelMeudec** [comment]
Hi! We're first trying to get up-to-date by merging the branchs that exist (A3C, PPO). We'll look into rainbow right after that!

**Comment by RaphaelMeudec** [comment]
Closing the issue as it is kind of a duplicate to #180
