### ISSUE TITLE
FR: more in docs on which does what

### ISSUE THREAD

**Issue by salamanders** [keras-rl/keras-rl#2]
I loved the blurb "DQN (for tasks with discrete actions) as well as for DDPG (for tasks with continuous actions)" and that you clearly say which one is best for which type of task. 

Can you do the same for the rest?  It really helps first time users pick the right one to start with.

**Comment by matthiasplappert** [comment]
Yes, I absolutely intend to. However, I'm currently pretty busy with a lot of other things, so I'm not sure when I'll get around to actually do it.

**Comment by salamanders** [comment]
Cool, not a rush.  Even a blurb as long as a few words helps!

**Comment by RyanHope** [comment]
If you enable the Wiki maybe some of us can start documenting things as we go.

**Comment by matthiasplappert** [comment]
That's a good idea–I've enabled the wiki tone editable by everyone.
