### ISSUE TITLE
pip install does not reflect current code?

### ISSUE THREAD

**Issue by olavt** [keras-rl/keras-rl#201]
I notice that when doing a "pip install keras-rl" the package does not contain the current (last checked in) version.

How often is the pip package updated?

**Comment by lechatthecat** [comment]
Just for your information, to install the latest from github:
`$ python3.5 -m pip install git+https://github.com/keras-rl/keras-rl.git`

**Comment by RaphaelMeudec** [comment]
Pypi has been updated, sorry for the delay!
