### ISSUE TITLE
How can I get the reward history from a training session?

### ISSUE THREAD

**Issue by mattdornfeld** [keras-rl/keras-rl#203]
I think the title basically says it. I'm having trouble figuring out how to do it from the docs alone.

**Comment by RaphaelMeudec** [comment]
Hi, you should have a look at the [FileLogger callback](https://github.com/keras-rl/keras-rl/blob/master/rl/callbacks.py#L286).

**Comment by olavt** [comment]
```
train_history = dqn.fit(…
train_rewards = train_history.history['episode_reward']
```
