### ISSUE TITLE
Pre-Populate Replay Buffer With Human Play

### ISSUE THREAD

**Issue by batu** [keras-rl/keras-rl#209]
Hello,

First of thank you for the great library. It has come in very handy in my research.

I am trying to set it up such that a human plays the first n episode, filling the DQN replay buffer with "Good Data" and then the algorithm starts taking actions on top of the base expert knowledge.

Is there a recommended way that I should go about updating the code?

Thank you very much,

**Comment by M00NSH0T** [comment]
I don't have generalized code yet that I can share, but I can chime in with some basic take aways I've had doing something similar. I've found that with a number of the Async methods, it helps to have a few threads dedicated to running the current policy, but then have a couple other threads that are feeding data from other policies completely unrelated to the state of the neural networks, which could be data from human played games, or perhaps data from the best practices policy. This all gets collected and fed to the buffer, which in turn trains the critic (and updates the actors). I don't think you necessarily just want to preload the buffer with human played games' results though. My gut says it's probably better to mix that data in with what it learns from exploration in the beginning and help nudge it along. Mix those results in, perhaps with a decreasing percentage of samples overtime, kind of like exploration.
