### ISSUE TITLE
How to train an agent with keras-rl?

### ISSUE THREAD

**Issue by yodahekinsew** [keras-rl/keras-rl#219]
Hi, I'm a beginner in RL and I'm trying to understand how to use these models and how to train agents with custom environments. 

I was trying to train an agent with the Hotter Colder environment which is included with Openai's gym environment. However, I keep getting an error that says "ValueError: Error when checking input: expected flatten_1_input to have 3 dimensions, but got array with shape (1, 1)"

If anyone can look at my code (which is below) and explain to me what I'm doing wrong, that would be great! Thank you!

import numpy as np
import gym
import gym.spaces

from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from keras.optimizers import Adam

from rl.agents.dqn import DQNAgent
from rl.policy import BoltzmannQPolicy
from rl.memory import SequentialMemory

ENV_NAME = 'HotterColder-v0'

env = gym.make(ENV_NAME)
np.random.seed(123)
env.seed(123)
nb_actions = env.action_space.shape[0]

model = Sequential()
print(model)
model.add(Flatten(input_shape= (1,env.observation_space.n)))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(nb_actions))
model.add(Activation('linear'))
print(model.summary())

memory = SequentialMemory(limit=50000, window_length=1)
policy = BoltzmannQPolicy()
dqn = DQNAgent(model=model, nb_actions=nb_actions, memory=memory, nb_steps_warmup=10,
               target_model_update=1e-2, policy=policy)
dqn.compile(Adam(lr=1e-3), metrics=['mae'])

dqn.fit(env, nb_steps=50000, visualize=False, verbose=2)

dqn.save_weights('dqn_{}_weights.h5f'.format(ENV_NAME), overwrite=True)

dqn.test(env, nb_episodes=5, visualize=True)

**Comment by artyemk** [comment]
Did you solve this problem?

**Comment by maifeng** [comment]
Figured out that I need to define my own class by editing the [source code of hotter_colder](https://github.com/openai/gym/blob/master/gym/envs/toy_text/hotter_colder.py) and let the observation state to be np.array().

e.g.
change
`self.observation = 2`
to
`self.observation = np.array([2])`

Do this for `__init__()`, `step()`, and `reset()`.

**Comment by jheffez** [comment]
The above solution from @maifeng  did not work. Any thoughts?
