### ISSUE TITLE
Add stochastic policy gradient

### ISSUE THREAD

**Issue by HenryJia** [keras-rl/keras-rl#22]
It would be nice to have stochastic policy gradient in this. It would help implement things like 
https://papers.nips.cc/paper/5542-recurrent-models-of-visual-attention.pdf

**Comment by matthiasplappert** [comment]
Do you mean something like this? http://www-anw.cs.umass.edu/~barto/courses/cs687/williams92simple.pdf

**Comment by HenryJia** [comment]
Yes, I am essentially referring to the REINFORCE method
