### ISSUE TITLE
keras-rl with LSTM possible ?

### ISSUE THREAD

**Issue by thusinh1969** [keras-rl/keras-rl#222]
Great library ! However it seems that it only support 2D observation input hence [batch, n_timesteps, features] LSTM as input does not support.

Can someone help me out here how to tweak the codes (where ?!) to make this work ? I have to work around by run a LSTM-VAE to get latent factors and then use the keras-rl lib for training, which is not bad but still am willing to try out direct LSTM training (which will be much slower I know).

Thanks you.
Steve

**Comment by miroblog** [comment]
maybe if you are using simple dqn, you could easily do ... 

> First:  tweak the env to return ... (n_timesteps, features) 
> Second: add Reshape layers before lstm

`model.add(Reshape((input_shape[1], input_shape[2]), input_shape=input_shape))
model.add(LSTM(128, activation='tanh', recurrent_activation='hard_sigmoid', return_sequences=True))`

something like this...
