### ISSUE TITLE
Multiple actions in DQN/DDPG

### ISSUE THREAD

**Issue by ahmadalattar242** [keras-rl/keras-rl#224]
Hello,
I was able to run the dqn and ddpg agents for discrete action spaces and continuous action spaces, respectively. However, I am wondering how can I have multiple actions as the ouput? 

For example, let's say I have a robot arm and I want to give it a contiuous value for its grip and a continuous value for its orientation. So instead of one action, I have two. What should I do to adapt to this requirement. Please provide as much detail and explanation as possible as I am just a beginner. 

Thank you!

**Comment by mirraaj** [comment]
@ahmadalattar242,  I think that is multiple output covered in ddpg. 

However, I personally do not recommend you to use DQN for multiple outputs. You need to define single output for multiple outputs. Suppose you have two possible actions for grip and two for orientation, you would need to define four actions which cover all the possible situation arising from the two action outputs. Please proceed ahead with DDPG. 

Let me know if anything is unclear to you.

**Comment by gvgramazio** [comment]
@mirraaj What you said about DQN and multiple outputs does apply also to continuous DQN? In this case, I think that there isn't anymore the curse of defining more outputs than actual actions. However, I don't know if continuos DQN are suitable for this type of environments. 

I'm not very skilled in the topic so, please correct me if I'm wrong and explain why continuous DQN are discouraged with multiple actions.
