### ISSUE TITLE
AssertionError: q_values.shape == (self.batch_size, self.nb_actions)

### ISSUE THREAD

**Issue by niclaswue** [keras-rl/keras-rl#248]
Hello,

first of all, thank you for creating this great library!
I'm using your DQN example together with a self-written gym environment. The environment is sending and receiving UDP packets with a simulation. After around an hour of successful execution, the script crashed with the following error:

> Traceback (most recent call last):
  File "/home/niclas/PycharmProjects/simulationGymEnvironment/keras-rl/agent.py", line 122, in <module>
    dqn.fit(env, callbacks=callbacks, nb_steps=5000000, log_interval=10000, verbose=0)
  File "/home/niclas/PycharmProjects/simulationGymEnvironment/venv/lib/python3.5/site-packages/rl/core.py", line 194, in fit
    metrics = self.backward(reward, terminal=done)
  File "/home/niclas/PycharmProjects/simulationGymEnvironment/venv/lib/python3.5/site-packages/rl/agents/dqn.py", line 285, in backward
    assert q_values.shape == (self.batch_size, self.nb_actions)
AssertionError

Right before that, I got a sequence number mismatch. Therefore, I assume that it somehow has to do with the input to the network, but I did check the shape before passing on the numpy array.

Do you have any idea what could be the cause of that? Or how to prevent this crash?

**Comment by mirraaj** [comment]
Assertion fails if the shape of output from the neural network is not equal to (self.batch_size, self.nb_actions) . Assuming that self.nb_actions do not change with time, I believe it has something to do with your batch size. Please look into your batch_size value when your script fails. 

You may be correct that it may have something to do with your network. Please check that your observation space should match with your input.

**Comment by niclaswue** [comment]
Yes, both values are constant. Additionally, I check the shape of the input and is correct. I’m not home a few days, but I will provide more information and hopefully a minimal example when I’m back.

**Comment by afernandezcanosa** [comment]
@niclaswue did you finally solve your problem? I'm facing a similar error with a custom gym environment that I'm training with DQN. 
Thanks in advance!

**Comment by iamdavie** [comment]
i am stuck with this same issue ....did anyone find a solution??
