### ISSUE TITLE
Input index not in list

### ISSUE THREAD

**Issue by dAmnation69** [keras-rl/keras-rl#251]
First of all, thank you for creating this great library!
I'm using your DDPG example. 

`self.critic_action_input_idx = self.critic.input.index(critic_action_input)` from `ddpg.py, Line 71`
 is throwing an error : 

> `<tf.Tensor 'input_2:0' shape=(?, 2) dtype=float32> is not in list`

I assume that it somehow has to do with the input to the network (Critic), but i am unable to find the cause. Can someone guide me.

Thanks

**Comment by mirraaj** [comment]
@dAmnation69 Thank you for your appreciation.

Could you please be a little specific about the example you are using. I have checked and ddpg_pendulum seems to be working fine. 

Thanks

**Comment by dAmnation69** [comment]
I figured it out. I was learning and wanted to implement DDPG from scratch. Using this repo as a blueprint. 
Thanks 👍
