### ISSUE TITLE
How to decay epsilon within the EpsGreedyQPolicy?

### ISSUE THREAD

**Issue by bertoloti** [keras-rl/keras-rl#253]
I was trying to implement the decay of epsilon using the EpsGreedyQPolicy but I don't seem to find the most intuitive way to implement it. Does anyone knows how to? 
I would like to decay the property of the class "eps" by a factor of epsilon_decay every episode (not step).
Thanks in advance!

**Comment by nathanmargaglio** [comment]
You could look at adapting the `LinearAnnealedPolicy` class in the `policy.py` file.  That uses steps, of course, but if you can't estimate the number of steps in an episode in a sufficient way, then you could probably write a similar policy that looks at the episodes instead.
