### ISSUE TITLE
Unable to run pdd.py

### ISSUE THREAD

**Issue by aayushsaxena15** [keras-rl/keras-rl#257]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question in the [Keras-RL Google group](https://groups.google.com/forum/#!forum/keras-rl-users) or [join the Keras-RL Gitter channel](https://gitter.im/keras-rl/Lobby) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras-RL. You can update with:
`pip install git+git://github.com/keras-rl/keras-rl.git --upgrade --no-deps`

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps`

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short). If you report an error, please include the error message and the backtrace.

**Comment by aayushsaxena15** [comment]
When I am trying to run pdd.py to test the pacman gameplay, I get the following error:


`Traceback (most recent call last):
  File "pdd.py", line 14, in <module>
    from rl.memory import PrioritizedMemory
ImportError: cannot import name 'PrioritizedMemory'`

I have installed keras-rl and AdvancedPacmanDQNs on my system and I am also following the correct directory structure. Can anyone please help me?

**Comment by kaddynator** [comment]
I am also having the same error:

` from rl.memory import PrioritizedMemory
ImportError: cannot import name 'PrioritizedMemory'`

Has anyone solved this ?

**Comment by mirraaj** [comment]
@aayushsaxena15 Could you please elaborate me your issue?

@kaddynator I believe PrioritizedMemory isn't supported in https://github.com/keras-rl/keras-rl/blob/master/rl/memory.py .
