### ISSUE TITLE
[feature-request] Add the possibility to load and store memory.

### ISSUE THREAD

**Issue by gvgramazio** [keras-rl/keras-rl#262]
In some cases, the memory could be even more important than weights. Also, it is independent with respect to the neural networks involved in the algorithm. I think that it could be good if there is the possibility to load and store memory. In these days I will try to implement it by myself but I don't know if you have some policy about merges for new features.

**Comment by mirraaj** [comment]
@gvgramazio, Please open a PR request. I will look into the codes once I get time. Feel free to contribute to the project.
