### ISSUE TITLE
Saving/Loading/resuming agent state and weights

### ISSUE THREAD

**Issue by jheffez** [keras-rl/keras-rl#288]
Hello, I noticed that loading saved weights results in test of untrained agent (using the breakoutagent example). I read that saving just the weights is not enough since the agent/model is not optimized. Is there a solution? Is using the keras model.save/load_model functions solve this?
Ref: https://keras.io/getting-started/faq/#how-can-i-use-pre-trained-models-in-keras

**Comment by Eriz11** [comment]
Hey jheffez, 

¿How did you solve this issue? I have trained an agent in a custom environment and after this process, I would want to use the trained and saved weights to restore the agent (I think that `load_weights` should be the way) and be able to deploy it into production; passing him the observations and getting the actions.

¿Is this doable with keras-rl actually? I recall that this could be done with keras as your post (using the `predict` methods available and feeding the `x` parameter). However, I don't see this possibility in the keras-rl docs.

Any help would be appreciated. Thanks in advance,

**Comment by krumiaa** [comment]
Would like help with the same, receiving an action prediction for a single observation instance in production setting. Can this be done with Keras-RL?
