### ISSUE TITLE
tf.keras?

### ISSUE THREAD

**Issue by jheffez** [keras-rl/keras-rl#291]
Hi All, it seems that more and more, Tensorflow-derived projects could benefit from each other. For example, using the TensorFlow/AdaNet AutoML to find the best model. In addition, ability to speed up training on colab TPU's by using the built-in function to convert tf.keras models to TPU-optimized ones. 

So I tried to convert the Keras code into tf.keras. However, it's not 1-to-1. Would it be possible to convert keras-rl to tf.keras to rip the above synergy benefits?

**Comment by AI-Guru** [comment]
Namaste. I began adapting a fork of Keras-RL to TensorFlow 2.0. I agree on the promised benefits. And yes. It is not 1-to-1.

Maybe somebody wants to join? 

https://github.com/AI-Guru/tf-keras-rl

**Comment by jheffez** [comment]
This is great!

**Comment by AI-Guru** [comment]
Maybe you want to join? I already got a couple of agents up and running and TF2-compatible.

**Comment by jheffez** [comment]
I'm not sure how helpful I can be, still learning this amazing field. What I can do is kick the tires and give feedback and possible solution (if I can). Thanks.

**Comment by AI-Guru** [comment]
That would be very appreciated!

**Comment by wau** [comment]
Updated code to function with TensorFlow 2 Keras ..[Keras-RL2](https://github.com/wau/keras-rl2)
Included merge requests containing multi input support.

All environments working with eager execution using tf-nightly-2.0-preview.

Installable with python package:
`pip install keras-rl2`

**Comment by jheffez** [comment]
Thank you!
