### ISSUE TITLE
load_weights() no work

### ISSUE THREAD

**Issue by kosoraYintai** [keras-rl/keras-rl#300]
I haved trained Pendulum-v0 and saved the model's weights, the model converged and the mean reward was about -200. But when I run the application again by using "load_weights()", the mean reward is about -1000. How can I sove it?

**Comment by giorgionicola** [comment]
Hi, I am facing the same problem with a custom environment, am I missing something in method load_weights()?

`agent = DDPGAgent( model parameters)`
`agent.compile([Adam(lr=1e-4), Adam(lr=5e-4)], metrics=['mae'])`
`agent.load_weights('weights/holed_wall_cart2_UR10_ddpg_v075.h5f'.format())`
`agent.test(env, nb_episodes=10, visualize=False, )`

that's the how I load the weights.
