### ISSUE TITLE
Plans to continue development?

### ISSUE THREAD

**Issue by jheffez** [keras-rl/keras-rl#303]
Hey all,
I noticed that it's been a while since last update. Are there plans to continue development?

**Comment by mirraaj** [comment]
Hello @jheffez, We have plans for the development of this repository. Presently most us are busy with work. I will contribute to this project from June 2019. I hope this delay doesn't create problems for you. In case, you need any help let me know.

**Comment by jheffez** [comment]
Hi @mirraaj, Thanks for the quick reply. Can you please shed light on a roadmap? Like taking advantage of faster/better RL technics? For example: Google recently proposed a new algorithm — Simulated Policy Learning, or SimPLe for short. [https://venturebeat.com/2019/03/25/google-researchers-improve-reinforcement-learning-by-having-their-ai-play-pong/](url)
[https://sites.google.com/view/modelbasedrlatari/home](url) 

Though these articles are Atari/ALE-centric I'd be interested also in more basic GYM environments (cartpole).

**Comment by daguito81** [comment]
Any answer regarding this?

**Comment by mirraaj** [comment]
@jheffez @daguito81 Apologies for such a delay. I am planning the current roadmap for the organization. I have been off from work for the last few weeks. I will keep you updated. :)
