### ISSUE TITLE
Keras-RL adding extra dimension to my input

### ISSUE THREAD

**Issue by ndeshp2s** [keras-rl/keras-rl#306]
Hello,

I am using keras-RL DQN to train my agent. My input is a 3-d tensor of size 16 x 9 x 4 (width,height,channel). Its not an RGB image, but features of environment. I wish to apply a convolution to this input. If I flatten the input with the flatten layer being "model.add(Flatten(input_shape=(1,) + (16,9,4)))" it works. 

However, for a convolutional layer, if I try "model.add(Conv2D(32, (3, 3), input_shape=(1,) + (16, 9, 4)))" or "model.add(Conv2D(32, (3, 3), input_shape=(16, 9, 4)))" it gives the following error:

"expected conv2d_1_input to have 4 dimensions, but got array with shape (1, 1, 16, 9, 4)".

I went though other discussion of this problem and there they convert an RGB image to gray scale image to reduce one dimension. However, for my case since its not an image, I wish to pass a 3d tensor only to the convolutional layer.

I am not sure why keras is adding this extra dimension to my input.

**Comment by fehlfarbe** [comment]
Hi, did you find a solution? I have a similar problem: https://groups.google.com/forum/#!topic/keras-rl-users/eg_z0V2S5yU

**Comment by fehlfarbe** [comment]
I found a solution for window_length=1 in #238 

My model:
With 32x32 images and 4 channels:
```
    width = height = 32
    layers = 4
    window_length = 1
    input_neurons = width * height * layers
    output_neurons = width * height
    input_shape = (layers, width, height)

    model = Sequential()
    model.add(Convolution2D(32, (4, 4), strides=(4, 4), input_shape=input_shape, data_format="channels_first"))
    model.add(Activation('relu'))
    model.add(Convolution2D(64, (2, 2), strides=(2, 2)))
    model.add(Activation('relu'))
    model.add(Convolution2D(32, (2, 2), strides=(1, 1)))
    model.add(Activation('relu'))
    model.add(Flatten())
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dense(output_neurons))
    model.add(Activation('linear'))
```

And my `process_state_batch` method:
```
    def process_state_batch(self, batch):
        # print("batch before: ", batch.shape)

        batch_samples = []
        for batch_sample in range(batch.shape[0]):
            sequence = []
            for frame in range(batch.shape[1]):
                sequence.append(batch[batch_sample][frame])
            sequence = np.concatenate(sequence, axis=0)
            sequence = np.expand_dims(sequence, axis=0)
            batch_samples.append(sequence)
        batch = np.concatenate(batch_samples, axis=0)

        # print("batch after: ", batch.shape)

        return batch
```

window_length > 1 does not work because the Convolution layer expects (channel, width, height) and the batch processor creates (channel*window_size, width, height).

**Comment by ndeshp2s** [comment]
Hi @fehlfarbe. Thanks so much for updating your code. I will give it a try today.

**Comment by fehlfarbe** [comment]
A more simple way was posted in: https://github.com/keras-rl/keras-rl/issues/229#issuecomment-482913659
Just return `numpy.squeeze(batch, axis=1)` in `process_state_batch`

**Comment by AloshkaD** [comment]
If anyone get stuck with the same issue and come here, below is my workaround. The suggested fixes here didn't work for me because my observation consist of images and 1d data, hence its a multi observation in one state. I did this in dqn.py

```    def compute_batch_q_values(self, state_batch):
        batch_samples = []
        batch = self.process_state_batch(state_batch)
        
        for i in batch:
            print('before',i.shape) 
            i=np.squeeze(i,axis=1)
            
            batch_samples.append(np.array(i))
            print('after',i.shape)
        batch =  batch_samples 
        
        q_values = self.model.predict_on_batch(batch)
        assert q_values.shape == (len(state_batch), self.nb_actions)
        return q_values
```
