### ISSUE TITLE
Visualize the loss history in keras-rl DQN

### ISSUE THREAD

**Issue by ndeshp2s** [keras-rl/keras-rl#307]
Hello,

Is there a way to record the loss history as well in keras-rl DQN. When I store the history, it seems to store the following 3 keys:
- 'nb_episode_steps'
- 'episode_reward'
- 'nb_steps'.

However, I cannot find any keys related to accuracy and loss.

**Comment by Qinusty** [comment]
I make use of [FileLogger](https://github.com/keras-rl/keras-rl/blob/master/rl/callbacks.py#L286) which stores metrics every step as shown [here](https://github.com/keras-rl/keras-rl/blob/master/rl/callbacks.py#L340). In my experience, loss is passed as a metric from the [agent.backward](https://github.com/keras-rl/keras-rl/blob/master/rl/core.py#L416) function but this is agent specific and metrics may vary (DQN definitely provides loss here).
