### ISSUE TITLE
All the examples deal with the problems using the discrete action space. I am wondering if I can use the multi_discrete action space. Can the DQNAgent  still work?

### ISSUE THREAD

**Issue by bugzhu** [keras-rl/keras-rl#310]
I am trying to using multi_discrete action space from gym with keras rl. However, all the examples in keras rl use discrete action space. I don't know how to use the DQNAgent to deal with the multi_discrete action space. In my idea, the DQNAgent always return the action scalar instead of the action vector.

**Comment by mirraaj** [comment]
@bugzhu Reinforcement learning algorithms have specific features and properties for discrete and continuous action spaced games. You may try the DDPG algorithm for the continuous action space environments.

Apologies for the delay in answer. :)
