### ISSUE TITLE
Actions values out of box limits.

### ISSUE THREAD

**Issue by mquinteiro** [keras-rl/keras-rl#314]
I have done a OpenAI env similar to Pendulum-v0, with this spaces:

```
self.observation_space = gym.spaces.Box(np.array([-1, -1, -1, -1, 0]), np.array([1, 1, 1, 1, 1]))
self.action_space = gym.spaces.Box(low=np.array([-1, 0]),high= np.array([1, 1]))
```
And I'm using the same Actor and Critic Networks and parameters than in the Pendulum DDPGAgent example.

Sometimes the the action[0] are outside the limits and other times the actios start to grow without limit with absurde values like 18755123. Also step is called with negative action[1].

Is it normal? I'm doing something wrong? That values don't make sense and make lost a lot of time.

**Comment by kanchi0914** [comment]
how about using 'tanh' function when activating output layer of actor network?
like following:
```
actor.add(Activation('tanh'))
```
Sorry if I have misunderstood, I think it clips output value from-1 to 1.

**Comment by nick-gorman** [comment]
Hi, I'm having a problem almost identical to that described by @mquinteiro . Any suggestions?

**Comment by TheTrash** [comment]
Maybe adding some dtype on the Box?
As i can see the pendulum has this declaration:

`self.action_space = spaces.Box(low=-self.max_torque, high=self.max_torque, shape=(1,), dtype=np.float32)`

`self.observation_space` = spaces.Box(low=-high, high=high, dtype=np.float32)`

**Comment by nick-gorman** [comment]
Doesn't fix the problem unfortunately

**Comment by BananaFructa** [comment]
Hello I am having the exact same issue. @nick-gorman did you manage to find anything that could fix it?
