### ISSUE TITLE
DDPG Agent batch shape problem

### ISSUE THREAD

**Issue by wmeints** [keras-rl/keras-rl#317]
The DDPG Agent wraps the data for the call to [`process_state_batch`](https://github.com/keras-rl/keras-rl/blob/e6efb0d8297ec38d704a3110b5d6ed74d09a05e3/rl/agents/ddpg.py#L197) with additional square brackets which is unnecessary and causes an error with the batch shape when `predict_on_batch` is called on the next line. In my case I'd expect the batch shape to be `(1, 5, 25)`, but it is turned into `(1,1,5,25)`.

Seems like that the additional brackets are unnecessary. The same thing is happening also in the DQNAgent. See: #306 and #229

**Comment by John-Almardeny** [comment]
`DDPG` implementation is not so robust. Agree with ya.
For example: `metrics += [mean_q]` in `compile()` function, causes `metrics` list to explode when we have multiple-agents.
