### ISSUE TITLE
Add Tensorflow 2 Keras Support

### ISSUE THREAD

**Issue by wau** [keras-rl/keras-rl#318]
Tensorflow 2 has been out natively supporting Keras integrations. I want to use my updated Tensorflow 2 with this repo. Keras-RL has been inactive in accepting merge requests.

Updated code to function with TensorFlow 2 Keras here: https://github.com/wau/keras-rl2

Included merge requests containing multi input support.

All environments working with eager execution using tf-nightly-2.0-preview.

Installable with python package:
`pip install keras-rl2`

**Comment by wau** [comment]
Awaiting accepting merge requests from repo admins..

**Comment by paralin** [comment]
Cool!

**Comment by bionicles** [comment]
thank you @wau

**Comment by duohedounai** [comment]
Thank you! It can really works. 
It will update to tensorflow 2.3 if you do this, so maybe you need to install the right version of tensorflow for your computer again. I use tensorflow-gpu 2.0, and it does works.
