### ISSUE TITLE
tanh activation result less than -1

### ISSUE THREAD

**Issue by salos1982** [keras-rl/keras-rl#327]
I'm trying to create my own environment and test it using DDPGAgent
I copied example ddpg_mujoco.py and replace with my environment
After some iterations I got exception that my function cannot choose descrete action because of action values passed into step function contains values less that -1 (exactly -1.0421247)

How it can be?

**Comment by bvrockwell** [comment]
Is your action space discrete or continuous?

**Comment by salos1982** [comment]
descrete. I found the reason. It is becuase of noise that is generated
