### ISSUE TITLE
AttributeError: module 'keras.backend' has no attribute 'image_dim_ordering'

### ISSUE THREAD

**Issue by stephenscki** [keras-rl/keras-rl#329]
Got this error when I tried running dqn_atari.py in examples directory:

Traceback (most recent call last):
  File "dqn_atari.py", line 58, in <module>
    if K.image_dim_ordering() == 'tf':
AttributeError: module 'keras.backend' has no attribute 'image_dim_ordering'

I had this issue myself during my research recently, but now you have to use image_data_format as either 'channels_first' or 'channels_last', or you can set it in the keras json file. [https://keras.io/backend/](url). Should be a simple fix.

**Comment by razzzu** [comment]
I think I had the same issue. Downgrade keras to 2.2.4
`pip install keras==2.2.4`
