### ISSUE TITLE
Using Keras-RL for anything other than the examples 

### ISSUE THREAD

**Issue by gregarious9612** [keras-rl/keras-rl#334]
Hi guys, I'm pretty new with RL in python and I ran into your Keras-RL library with the intention of using it for a game that isn't one of the examples provided. I was wondering if you guys were able to provide some guidance into what I should create wrappers for, to use the algorithms and library in general for any game/RL problems. I would go to the documentation link you guys have provided, but it seems incomplete.

**Comment by stefanbschneider** [comment]
You basically need to use/create a Gym environment of the game that you can use when you call `agent.fit(env, ...)` to train the agent on the environment.
