### ISSUE TITLE
AttributeError: 'Adam' object has no attribute '_name'

### ISSUE THREAD

**Issue by palbha** [keras-rl/keras-rl#345]
I am having the above errro while running the dqn_cartpole example.

I am using the below versions 
tensorboard                        1.13.1
tensorflow                         2.0.0b0
tensorflow-estimator               1.13.0
Keras                              2.3.0
Keras-Applications                 1.0.8
Keras-Preprocessing                1.1.0
keras-rl                           0.4.2
keras-rl2                          1.0.3
gym                                0.10.5

Please let me know what should be done as due to this issue I wont be able to utilize the DQNAgent in keras-rl

**Comment by jp-null** [comment]
Hello! I haven't posted at all here but I got the same problem as you and recently and I solved it by downgrading a lot of packages though pip. You may want to give it a shot:

`pip install keras==2.0.6`
`pip install numpy==1.16.4`
`pip install keras-rl==0.3.1`
`pip install tensorflow==1.13.1`

You may get an error saying keras-rl requires tensorflow 2.0, but ignore it, the Cart example should run just fine.

**Comment by timothe-chaumont** [comment]
I added a fake attribute called `_name` to the optimizer and the error disappeared.

`from tensorflow.python.keras.optimizers import Adam`
`Adam._name = 'hey'`

If it is only a name, It should not affect the operation of the package.

**Comment by MattisIsEpic** [comment]
> I added a fake attribute called `_name` to the optimizer and the error disappeared.
> 
> `from tensorflow.python.keras.optimizers import Adam` `Adam._name = 'hey'`
> 
> If it is only a name, It should not affect the operation of the package.



> I added a fake attribute called `_name` to the optimizer and the error disappeared.
> 
> `from tensorflow.python.keras.optimizers import Adam` `Adam._name = 'hey'`
> 
> If it is only a name, It should not affect the operation of the package.
timothe, you are a certified life saver.
