### ISSUE TITLE
EXAMPLE : Loading Models After fully trained

### ISSUE THREAD

**Issue by STRATZ-Ken** [keras-rl/keras-rl#350]
Is there any examples out there that consist of a model after its trained with keras-rl that can be loaded and then used?  

When I attempt to model.save() at the end, then load that with keras.load_model(), the data from the prediction is completely wrong.  

If I save the weights, reload with keras-rl, and run the prediction, my answers are correct.  

I would prefer to avoid having to creating a DQNAgent, with all the parameters, then load the weights, then predict through that.  

Is that possible?

**Comment by ingambe** [comment]
In the DQN atari example, there is an example about how to implement a train and test mode https://github.com/keras-rl/keras-rl/blob/216c3145f3dc4d17877be26ca2185ce7db462bad/examples/dqn_atari.py#L103

**Comment by STRATZ-Ken** [comment]
Yeah, but see, here is an example of having to create the DQNAgent first.  Then loading the weight to that.  Shouldn't we be able to just save the model from the train, and load keras.load_model without having to do anything with keras-rl?

**Comment by ingambe** [comment]
Ah okay, I see
First be sure to have **h5py** dependency installed: [How can I install HDF5 or h5py to save my models in Keras?](https://keras.io/getting-started/faq/#how-can-i-install-hdf5-or-h5py-to-save-my-models-in-keras) beware, for debian based distrib you need to install **libhdf5** as explained in the doc
Then as you mentioned you need to use model.save() and load_model(): [https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model](https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model)

**Comment by STRATZ-Ken** [comment]
I will give this a shot, still haven't finalized my model, as I am getting some wonkeness, but once I have something that I feel it a good fit, I will try this.

**Comment by STRATZ-Ken** [comment]
When I do this, I am not getting the same results as I would from loading the weights.  The models look honestly, completely different.  The output values make no sense when I do the same query with load_weights vs load_model.

**Comment by rodrigo2019** [comment]
did you solved it?
