### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by khayamgondal** [keras-rl/keras-rl#354]
I see last commit was made in November 2019. Looks like no new work is going on.

**Comment by yingshaoxo** [comment]
Repositorys at GitHub won't die as long as you contributed to it.

Pull request is welcomed.

**Comment by msat59** [comment]
But

> Repositorys at GitHub won't die as long as you contributed to it.
> 
> Pull request is welcomed.

But there are so many PRs waiting for approval !
