### ISSUE TITLE
Module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

### ISSUE THREAD

**Issue by rhalaly** [keras-rl/keras-rl#377]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question in the [Keras-RL Google group](https://groups.google.com/forum/#!forum/keras-rl-users) or [join the Keras-RL Gitter channel](https://gitter.im/keras-rl/Lobby) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras-RL. You can update with:
`pip install git+git://github.com/keras-rl/keras-rl.git --upgrade --no-deps`

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps`
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short). If you report an error, please include the error message and the backtrace.

Running the code from `examples/dqn_cartpole.py` throws an error:

```
  File "***", line 8, in <module>
    from rl.agents.dqn import DQNAgent
  File "***\site-packages\rl\agents\__init__.py", line 2, in <module>
    from .dqn import DQNAgent, NAFAgent, ContinuousDQNAgent
  File "***\site-packages\rl\agents\dqn.py", line 4, in <module>
    import keras.backend as K
  File "***\site-packages\keras\__init__.py", line 20, in <module>
    from . import initializers
  File "***\site-packages\keras\initializers\__init__.py", line 124, in <module>
    populate_deserializable_objects()
  File "***\site-packages\keras\initializers\__init__.py", line 82, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
```

Using the latest Keras and Keras-RL

**Comment by dioscuroi** [comment]
I've got the same problem. Have you solved the issue?

**Comment by rhalaly** [comment]
No, but I closed the issue since this package is dead...
