### ISSUE TITLE
Undocumented version requirements for python, tensorflow, and keras

### ISSUE THREAD

**Issue by jakurucar** [keras-rl/keras-rl#378]
It's unclear what compatible versions of tensorflow, keras, and python this works with. Please document in readme so we can make sure we are using the right versions if we want to leverage your algorithms.

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question in the [Keras-RL Google group](https://groups.google.com/forum/#!forum/keras-rl-users) or [join the Keras-RL Gitter channel](https://gitter.im/keras-rl/Lobby) and ask there instead of filing a GitHub issue.

Thank you!

- [ x] Check that you are up-to-date with the master branch of Keras-RL. You can update with:
`pip install git+git://github.com/keras-rl/keras-rl.git --upgrade --no-deps`

- [ x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps`

- [n/a ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short). If you report an error, please include the error message and the backtrace.

**Comment by loneosama** [comment]
actually, i was looking through the code and the code uses keras library not the tensorflow.keras which might lead to problems. I think one simple (yet which can be exhausting easily) is to shift this code to tensorflow.keras otherwise it wont work with any new keras version

**Comment by loneosama** [comment]
one more thing [Keras](https://keras.io/examples/rl/) officially has started to add algorithms. but the list still seems short 
I think we can simply shift the documentation and the implemented algorithms from here to there?
