### ISSUE TITLE
Training performance is quite slow

### ISSUE THREAD

**Issue by Cpt-Falcon** [keras-rl/keras-rl#379]
I was trying to run an something similar to the atari program but with real training. Training is very slow with an rtx 2070. 

Keras RL is not using the nvidia optimized CUDNN libraries. Online i was seeing that the atari training example can take up to 40 hours on a tesla K40. That seems really high to me.

Is it expected for training to take that long, are there any optimizations that can accelerate things?

**Comment by yosoul93** [comment]
You have to install tensorflow-gpu and change keras to tensorflow.keras
Hope this helps

**Comment by Cpt-Falcon** [comment]
> You have to install tensorflow-gpu and change keras to tensorflow.keras
> Hope this helps

Thanks for the reply. Using tensorflow-gpu with an RTX 2070 cuts performance in half. I might not be using the cuDNN kernel and instead using the generic kernel, but still it shouldn't be that slow right?
