### ISSUE TITLE
Submit Pull request to keras-contrib?

### ISSUE THREAD

**Issue by ahundt** [keras-rl/keras-rl#69]
Keras has created a new official keras-contrib repository where they will accept a broader range of contributions than mainline keras, for eventual inclusion in mainline if it becomes widely used. Would you consider moving keras-rl there?

https://github.com/farizrahman4u/keras-contrib

**Comment by bstriner** [comment]
@matthiasplappert even if you don't merge it in, I think we need a good listing of keras-related paraphernalia. Maybe we write up a sentence or two and make a central listing in keras-contrib?
